### ISSUE TITLE
does not contain a method 'propertyOrParam'

### ISSUE THREAD

**Issue by webeks** [CGGStudio/cookielawbanner#2]
An exception has been thrown during the rendering of a template ("The component 'CGGStudio\Cookielawbanner\Components\Cookielawbanner' does not contain a method 'propertyOrParam'.").

**Comment by Adrion** [comment]
propertyOrParam was removed from OctoberCMS 
check : https://github.com/octobercms/october/commit/9927568d980d57851e182bb87c395a3c2a7cbce3

**Comment by MassiwaDev** [comment]
An exception has been thrown during the rendering of a template ("The component 'CGGStudio\Cookielawbanner\Components\Cookielawbanner' does not contain a method 'propertyOrParam'.").
